# Generated by Django 6.1.1 on 2026-09-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_sitesettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('tooth', 'Tooth'), ('shield', 'Shield'), ('smile', 'Smile'), ('crown', 'Crown'), ('zap', 'Laser'), ('sparkle', 'Sparkle'), ('moon', 'Sedation'), ('drop', 'Gums'), ('xray', 'X-ray'), ('scan', 'Scan'), ('heart', 'Heart'), ('wallet', 'EMI / Wallet'), ('cal', 'Calendar'), ('clipboard', 'Clipboard')], default='shield', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why choose us point',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisitStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('tooth', 'Tooth'), ('shield', 'Shield'), ('smile', 'Smile'), ('crown', 'Crown'), ('zap', 'Laser'), ('sparkle', 'Sparkle'), ('moon', 'Sedation'), ('drop', 'Gums'), ('xray', 'X-ray'), ('scan', 'Scan'), ('heart', 'Heart'), ('wallet', 'EMI / Wallet'), ('cal', 'Calendar'), ('clipboard', 'Clipboard')], default='cal', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Visit step',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='branches_title',
            field=models.CharField(default='Two clinics in Chennai', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_text',
            field=models.CharField(blank=True, default='Book your visit today. Pay in easy instalments with no-cost EMI.', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title',
            field=models.CharField(default='Ready for a healthier smile?', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='doctors_title',
            field=models.CharField(default='Meet our specialists', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_text',
            field=models.CharField(blank=True, default='Move across the photo to compare the smile before and after treatment.', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_title',
            field=models.CharField(default='Real results, real smiles', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(default='Trusted dental care in Chennai', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_highlight',
            field=models.CharField(blank=True, default='confident smile', help_text='Part of the headline shown in light blue', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_text',
            field=models.CharField(blank=True, default='Treatments for every age and need, explained clearly before we begin.', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_title',
            field=models.CharField(default='Complete care for every smile', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='visit_title',
            field=models.CharField(default='Simple from start to smile', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='why_highlight',
            field=models.CharField(blank=True, default='our priority', help_text='Part of the title shown in blue', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='why_image',
            field=models.ImageField(blank=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='why_image_small',
            field=models.ImageField(blank=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='why_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='why_title',
            field=models.CharField(default='Your smile, our priority', max_length=150),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show on home page'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Digits with country code, e.g. 919876543210', max_length=20),
        ),
    ]
