# Generated by Django 6.0.3 on 2026-09-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_homefeature_visitstep_sitesettings_branches_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='technology_list',
            field=models.CharField(blank=True, help_text='Pipe-separated list shown as chips, e.g. Digital X-Ray|Intraoral Scanner|Laser Dentistry', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_title',
            field=models.CharField(default='What our patients say', max_length=150),
        ),
    ]
