# Generated by Django 6.0.3 on 2026-09-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_sitesettings_technology_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cta_image',
            field=models.ImageField(blank=True, upload_to='home/'),
        ),
    ]
