# Generated by Django 6.0.3 on 2026-09-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='highlight',
            field=models.CharField(blank=True, help_text='Short reaction shown in a speech bubble, e.g. "Feels like me again!"', max_length=40),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, upload_to='testimonials/'),
        ),
    ]
