# Generated by Django 6.1.1 on 2026-09-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, choices=[('tooth', 'Tooth'), ('shield', 'Shield'), ('smile', 'Smile'), ('crown', 'Crown'), ('zap', 'Laser'), ('sparkle', 'Sparkle'), ('moon', 'Sedation'), ('drop', 'Gums'), ('xray', 'X-ray'), ('scan', 'Scan'), ('heart', 'Heart'), ('wallet', 'EMI / Wallet'), ('cal', 'Calendar'), ('clipboard', 'Clipboard')], max_length=50),
        ),
    ]
